### ISSUE TITLE
Update urls in documentation from ecosystem to new github pages location

### ISSUE THREAD

**Issue by woodsp-ibm** [qiskit-community/qiskit-algorithms#124]
There are a number of files with links to the docs in `qiskit.org/ecosystem`  that need updating to the new location as follow-up after #115

- [x] setup.py  (see #125)
- [x] readme.md  (see #125)

and also

- [x] ~a number of tutorial notebooks~ #142 updated links except for Aer so now only 01 and 03 tutorials need updating for the couple of Aer links in each once the Aer docs are deployed in a new location. Aer urls updated by #147

and I listed this separately since the notebooks have links to Aer ~and Nature for which maybe its better to wait until they are all migrated off ecosystem and update them just the once~. The redirects will suffice for now.
